### ISSUE TITLE
Issues with snapshots deleting

### ISSUE THREAD

**Issue by accloudcoder** [pbudzon/aws-maintenance#15]
Thank you for this Paulina, I have implemented via the template and it is working.  However, the snapshots in the target region do not seem to be deleting and nothing in the cloudwatch logs suggest that the deletion is happening either.  I ran into an AWS limit of not being able to have over 100 manual snapshots so am having to manually delete them.  Have you seen this issue or maybe know a possible cause?  Thank you @pbudzon

**Comment by pbudzon** [comment]
Hi @accloudcoder 
Can you take a look at the logs - it should log either an exception ("No snapshots for cluster abc found in target region") or a simple message ("No old snapshots to remove in target region") - can you see if either of those is present?
Otherwise, there should be a message saying "Found X snapshot(s) to remove" at least.

Can you see either of those messages in the logs for Lambda? Do you have this problem with Aurora or non-Aurora databases?
