### ISSUE TITLE
CloudFormation stack fails if created in non-source region

### ISSUE THREAD

**Issue by fsantarelli** [pbudzon/aws-maintenance#4]
Hi @pbudzon - when trying to deploy the CloudFormation stack for cross-region RDS snapshot copy to the **destination region** the stack creation fails. Our snapshots are encrypted.

The evidence is in the third post - the previous image on this post was from a different Lambda function.

Many thanks!

**Comment by pbudzon** [comment]
Hi @fsantarelli 

This seems to be an error from Lambda, not CloudFormation. Can you confirm that the CF stack was created successfully, but you're getting this error when the Lambda itself tries to run?

**Comment by fsantarelli** [comment]
Hi @pbudzon and sorry for the mess - somehow I copied the logs from a different function that I was trying to use before. 

The CloudFormation creation rollsback and doesn't export any logs to CloudWatch, so here's a print from the CF events tab after the rollback:

![image](https://user-images.githubusercontent.com/20211639/35109413-32e5ef9e-fc6e-11e7-8a3e-1fd163c31af8.png)

Please let me know if you prefer me to edit my first post or maybe raise a cleaner issue report and delete this one. :)

**Comment by fsantarelli** [comment]
Hi @pbudzon and sorry for the mess - somehow I copied the logs from a different function that I was trying to use before.

The CloudFormation creation rollsback and doesn't export any logs to CloudWatch, so here's a print from the CF events tab after the rollback:

![image](https://user-images.githubusercontent.com/20211639/35109781-3b733f6c-fc6f-11e7-8338-acca414e2f6b.png)

Please let me know if you prefer me to edit my first post or maybe raise a better issue report and delete this one. :)

**Comment by pbudzon** [comment]
Hi @fsantarelli 

RDS events work only on RDS instances for the same region, so the Lambda can only subscribe to RDS instances within the region it's created... I don't know why I forgot about this, when I was writing the README, apologies. I'll update the README and simplify the CF stack (since there's no need to specify SOURCE_REGION explicitly) later today. 

The short answer is: the stack needs to be in the same region as RDS instances you want to use it for. 

Feel free to modify the first post to match this. The encrypted snapshots may be another thing completely - can you test with fixes from #3 and see if it works on your encrypted database? I'm guessing it will fail, since KMS keys are region-specific, so cross-region copy needs to specify a new key (in the target region), that RDS can use to re-encrypt the copied snapshot. If that's the case, please open another issue, and I'll take a look at adding support for KMS.

Thanks!

**Comment by fsantarelli** [comment]
Hi @pbudzon - no problem and many thanks again for the help.

I've just tested the Lambda and yes, it needs the KMS key to copy the encrypted snapshot. I'll raise a specific issue with the logs I've just collected.

**Comment by pbudzon** [comment]
Removed the source region parameter from CF template, since it has to be the same as the source region where the stack is being created and added that info to the README.

Thanks for the report!
